### ISSUE TITLE
Alkalmazás - Lista komponens elkészítése

### ISSUE THREAD

**Issue by krook1024** [krook1024/SZFM_2020_1_KP#58]
Meg kell jeleníteni a stateből a listában szereplő elemeket. A designtervhez igazodni kell!

![pic-selected-200921-1104-30](https://user-images.githubusercontent.com/9162926/93750014-27201b00-fbfb-11ea-9369-f6f03e5078de.png)

**Comment by krook1024** [comment]
Kis segítség:

Importálni való:
```js
import { useTodoState, useTodoDispatch } from "../context/todo-context";
```

Listák, jelenlegi aktív lista lekérése
```js
const { lists, current } = useTodoState();
```

Itt vannak a todo elemek:
```js
lists[current].todos
```

Dispatch függvény lekérése:
```js
  const dispatch = useTodoDispatch();
```

Megjelölés készként:
```js
dispatch({
  type: "complete_item",
  payload: {
    listId: current,
    itemId: index,
  },
});
```

**Comment by fulekylaszlo** [comment]
> Kis segítség:
> 
> Importálni való:
> 
> ```js
> import { useTodoState, useTodoDispatch } from "../context/todo-context";
> ```
> 
> Listák, jelenlegi aktív lista lekérése
> 
> ```js
> const { lists, current } = useTodoState();
> ```
> 
> Itt vannak a todo elemek:
> 
> ```js
> lists[current].todos
> ```
> 
> Dispatch függvény lekérése:
> 
> ```js
>   const dispatch = useTodoDispatch();
> ```
> 
> Megjelölés készként:
> 
> ```js
> dispatch({
>   type: "complete_item",
>   payload: {
>     listId: current,
>     itemId: index,
>   },
> });
> ```

Köszönöm!
